on:
  push:
    branches:
      - "main"

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - run: npm test

  release:
    runs-on: ubuntu-22.04
    needs: [test]
    steps:
      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
